Use list of arguments instead of a string for Popen()
On Ubuntu 20.04, using a string gives this error:

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/miniconda/bin/tensorboard --logdir workspace/tensorboard --port 6006 --samples_per_plugin=images=100'